### ISSUE TITLE
Make a version of  Awesome Emoji Picker  for google chrome

### ISSUE THREAD

**Issue by RandomPenguin1778** [rugk/awesome-emoji-picker#117] opened 2021-07-02 05:43 UTC
Hi ✨ Awesome Emoji Picker  Team !
Can anyone port a version of  Awesome Emoji Picker  for google chrome ?

**Comment by tdulcet** [comment] 2021-07-02 08:02
This is a duplicate of #54.

FYI, I have already done this and I have a PR ready that I will submit as soon as #93 is merged, as it has dependencies on changes made there. To publish on the Chrome Web Store, someone would need to donate the $5 for the required registration fee.

**Comment by rugk** [comment] 2021-07-02 13:23
Duplicate of https://github.com/rugk/awesome-emoji-picker/issues/54

**Closed by rugk** 2021-07-02 13:23 UTC
Labels: enhancement

**Comment by RandomPenguin1778** [comment] 2021-07-07 17:21
Hi, 
Can you at least convert the extension into a .crx file ?

**Comment by rugk** [comment] 2021-07-07 18:13
Again, let's discuss that in https://github.com/rugk/awesome-emoji-picker/issues/54.

In general, you can just rename the file to `.crx` and it may work. Likely you may at least have to adjust the `manifest.json`.
Again, @RandomPenguin1778, feel free to submit a PR to #54 if you know things that need to be adjusted.

See also the [resources linked here](https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/) for how to port extensions.
