### ISSUE TITLE
addon breaks composer

### ISSUE THREAD

**Issue by gene-git** [rugk/awesome-emoji-picker#132] opened 2022-07-11 09:29 UTC
## Bug description
When AEP is active - typing any text in thunderbird composer window and presss ENTER key - an extra unwanted blank line is inserted.
Turn it off and this goes away.

**Comment by tdulcet** [comment] 2022-07-11 09:39
Duplicate #129.

**Comment by gene-git** [comment] 2022-07-11 09:43
missed that - indeed its the same bug

**Comment by rugk** [comment] 2022-07-11 15:51
Duplicate of https://github.com/rugk/awesome-emoji-picker/issues/129

**Closed by rugk** 2022-07-11 15:51 UTC
Labels: bug, duplicate
